### ISSUE TITLE
BUG FOUND

### ISSUE THREAD

**Issue by username669** [donno2048/Rosehip#1]
I'm using linux and windows 10 home on my vm, when running b.bat I get the following messege:
```
curl: (77) schannel: next InitializeSecurityContext failed: SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by an authority that is not trusted.
```

**Comment by donno2048** [comment]
You need to download, install and add python to your PATH manually, then press a

**Comment by donno2048** [comment]
Or you can add ` -k` at the end of b.bat

**Comment by username669** [comment]
thanks, I added ` -k` and now its working

**Comment by donno2048** [comment]
I fixed the code....
Thanks for the feedback
